config/routes.rb
Rails.application.routes.draw do
  devise_for :userlogins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :postimages
  resources :posttexts
  resources :articles
  
  resource :articles do 
    resources :postimages
    resources :posttexts
  end

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  has_many :posttexts
  has_many :postimages
  scope :published, -> { where(published: true)}
  scope :public_article, -> { where( 'date_up <= ?', Time.now) }
  scope :no_public_article, -> { where( 'date_up > ?', Time.now) }
end

app/models/postimage.rb
class Postimage < ApplicationRecord
  belongs_to :article
  mount_uploader :image, ImageUploader
  validates :headline, presence: true
end

app/models/posttext.rb
class Posttext < ApplicationRecord
  belongs_to :article
  validates :headline, presence: true
end

app/models/userlogin.rb
class Userlogin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_articles, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.public_article
  end

  def show
    @articles_att = (@article.postimages + @article.posttexts).sort_by &:order_show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    return redirect_to articles_url, notice: 'You have sucsessfully created the article' if @article.save
    flash[:alert] = 'An Error'
    render :new    
  end

  def edit
    render :new
  end

  def update
    return redirect_to articles_url, notice: 'Update sucessfully' if @article.update(article_params)
    flash[:notice] = 'Update sucessfully'
    flash[:notice] = 'Update error'
    render :new
  end

  def destroy
    return redirect_to articles_url, notice: 'Destroy sucessfully' if  @article.destroy
    flash[:notice] = 'Destroy error'
    redirect_to articles_url

  end

  private
  def get_articles
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :published, :like)
  end

end

app/controllers/postimages_controller.rb
class PostimagesController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
 
  def index
    @postimages = Postimage.order('created_at DESC')
  end
 
  def show
  end
 
  def new
    @postimage = Postimage.new
  end
 
  def create
    @postimage = Postimage.new(postimage_params)
    return redirect_to postimages_url, notice: 'You have sucsessfully created the postimage' if @postimage.save
    flash[:alert] = 'An Error'
    render :new
  end
 
  def edit
    render :new
  end
 
  def update
    return redirect_to postimages_url, notice:'Update sucessfully' if @postimage.update(postimage_params)
    flash[:notice] = 'Update sucessfully'
    flash[:notice] = 'Update error'
    render :new    
  end

  def destroy    
    return redirect_to postimages_url, notice: 'Destroy sucessfully' if @postimage.destroy
      flash[:notice] = 'Destroy sucessfully'
      flash[:notice] = 'Destroy error'
      redirect_to postimage_url
  end
 
  private

  def set_post
    @postimage = Postimage.find(params[:id])
  end 
  def postimage_params
    params.require(:postimage).permit(:headline, :body, :order_show, :image, :article_id)
  end
 

end

app/controllers/posttexts_controller.rb
class PosttextsController < ApplicationController
  before_action :set_posttext, only: [:show, :edit, :update, :destroy]

  def index
    @posttexts = Posttext.all
  end

  def show

  end

  def new
    @posttext = Posttext.new
  end

  def create
    @posttext = Posttext.new(posttext_params)
    return redirect_to posttexts_url, notice: 'You have sucsessfully created the potstext' if @posttext.save
    flash[:alert] = 'An Error'
    render :new
  end

  def edit
    render :new
  end


  def update
    return redirect_to posttexts_url, notice: 'Update sucessfully' if @posttext.update(posttext_params)
    flash[:notice] = 'Update error'
    render :new
  end

  def destroy
    return redirect_to posttexts_url, notice: 'Destroy sucessfully' if @posttext.destroy
    flash[:notice] = 'Destroy error'
    redirect_to posttext_url
  end

  private

  def set_posttext
    @posttext = Posttext.find(params[:id])
  end

  def  posttext_params
    params.require(:posttext).permit(:headline, :content, :order_show, :like, :article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.slim
center 
  h1 Articles
p.btn
  = link_to 'Add new Articles', new_article_path() 
br
div.containter
  table.table.table-striped
    thead
      tr
        td Title
        td Like
        td Edit
        td Read
        td Delete
    tbody
      - @articles.each do |article| 
          tr        
            td 
              p = article.title
            td 
              p = article.like 
            td 
              span.edit_article_btn = link_to 'Edit', edit_article_path(article)  
            td 
              span = link_to 'Read', article_path(article)    
            td 
              span  = link_to 'Delete', article_path(article), method: :delete, 
                      data: {confirm: 'Are you sure want to delete this article'}
  hr

app/views/articles/new.html.slim
center
  h1 New Article
div.container
  = form_for @article do |f|
    div
      = f.label :title 
      = f.text_field :title, class: 'form-control' 
      = f.submit 

= link_to 'Back', articles_path 

app/views/articles/show.html.slim
div.container
  h1.title_article 
    = @article.title 
  - @articles_att.each do |att| 
    - if att.try(:image) 
        div.border_box
          p = att.headline 
          p = image_tag(att.image.url, alt: 'Image') if att.image?
        hr 
    - else 
        div.border_box
          p = att.headline 
          p = att.content
          p = link_to 'Edit', edit_posttext_path(att.id) 
        hr

p 
  = link_to 'Edit', edit_article_path(@article)   
  = link_to 'Back', articles_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Railsarticle
    = csrf_meta_tags 

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
  body
    - flash.each do |name, msg| 
     = content_tag :div, msg, class: name  
    = yield

app/views/postimages/_form.html.slim
div.container
  = semantic_form_for @postimage do |f| 
    div
      = f.label :headline 
      = f.text_field :headline, class: 'form-control' 

    div
      = f.label :order_show
      = f.text_field :order_show, class: 'form-control' 

    div
      = f.label :body
      = f.text_area :body, class: 'form-control' 
   
    div
      = f.label :image 
      = f.file_field :image, class: 'btn btn-default' 
    br
    div
       = f.input :article  

    = f.submit 

  div
    = link_to 'Back', postimages_path 

app/views/postimages/_postimage.slim
h2
  = link_to postimage.headline, postimage_path(postimage) 
p
  = truncate(postimage.body, length: 150) 
p 
  = image_tag(postimage.image.url, alt: 'Image') if postimage.image? 
p 
  = link_to 'Edit', edit_postimage_path(postimage)  
  = link_to 'Read', postimage_path(postimage) 
  = link_to 'Delete', postimage_path(postimage), method: :delete, 
          data: {confirm: 'Are you sure want to delete this post image '} 
hr

app/views/postimages/index.html.slim
center
  h1 
   Post Images
div.container
  div.btn
    = link_to 'Add post image', new_postimage_path
    = render @postimages 

app/views/postimages/new.html.slim
center
  h1 Post image
 
= render 'form', postimage: @postimages 

app/views/postimages/show.html.slim
div.container
  h1
    = @postimage.headline 
  p = image_tag(@postimage.image.url, alt: 'Image') if @postimage.image? 
  p = @postimage.body 
  p = link_to 'Edit', edit_postimage_path(@postimage)  
  p = link_to 'Back', postimages_path 

app/views/posttexts/_form.html.slim
div.container
  = semantic_form_for @posttext do |f| 
    div
      = f.label :headline 
      = f.text_field :headline, class: 'form-control' 
    div
      = f.label :order_show 
      = f.text_field :order_show, class: 'form-control'  

    div
      = f.label :content 
      = f.text_area :content, class: 'form-control' 
    br
    div
      = f.input :article 
    = f.submit 
  div = link_to 'Back', posttexts_path 

app/views/posttexts/_posttext.slim
- @posttexts.each do |posttext| 
  b
    p = posttext.headline
    p = posttext.content
    p = posttext.like 
    span = link_to 'Edit', edit_posttext_path(posttext) 
    span = " | "
    span = link_to 'Read', posttext_path(posttext) 
    span = " | "
    span = link_to 'Delete', posttext_path(posttext), method: :delete, 
          data: {confirm: 'Are you sure want to delete this post image '}    
  hr

app/views/posttexts/index.html.slim
center
  h1 Post Texts
div.container
  div = link_to 'Create Post Text', new_posttext_path 
  br
    = render @posttexts

app/views/posttexts/new.html.slim
center
  h1 Post text 
= render 'form', posttext: @posttexts   

app/views/posttexts/show.html.slim
div.container
  h1 = @posttext.headline 
  p = @posttext.content
  span = link_to 'Edit', edit_posttext_path(@posttext)  
  span = " | "
  span = link_to 'Back', posttexts_path 